import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Apple EULA | ROAMI AI",
};

export default function AppleEULA() {
  return (
    <div className="container mx-auto px-6 py-24 max-w-4xl flex-1 animate-fade-in">
      <div className="inline-block px-3 py-1 bg-primary/10 text-primary rounded-full text-sm font-medium mb-6">Legal</div>
      <h1 className="text-4xl md:text-5xl font-bold mb-8 text-foreground tracking-tight">End User License Agreement (EULA)</h1>
      
      <div className="space-y-8 text-subtext leading-relaxed">
        <p className="font-medium text-foreground">Effective Date: March 24, 2026</p>
        
        <p>This End User License Agreement ("Agreement") is a legal agreement between you ("User") and Roami AI™, a product of Whitney Justine, LLC ("Company," "we," "us," or "our"), governing your use of the Roami AI™ mobile application and related services (the "App"). By downloading, installing, or using the App, you agree to be bound by this Agreement. If you do not agree, do not use the App.</p>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">1. License Grant</h2>
           <p>Roami AI™ grants you a limited, non-exclusive, non-transferable, revocable license to use the App solely for personal, non-commercial purposes on a device you own or control, subject to the terms of this Agreement.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">2. Nature of the Service</h2>
           <p>Roami AI™ is an emotionally intelligent, AI-powered travel companion that provides personalized recommendations and travel guidance. The App is designed to support — not replace — your independent judgment. All travel decisions remain solely yours.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">3. Eligibility & Age Requirement</h2>
           <p>You must be at least 18 years of age to use the App. If you are under 18 years of age, you represent that you are not permitted to use the App. By using the App, you represent and warrant that you meet these eligibility requirements.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">4. AI-Generated Content Disclaimer</h2>
           <p>Content generated by Roami AI™ may be incomplete, inaccurate, or outdated. You agree to verify important details — including but not limited to hours of operation, reservations, pricing, transit schedules, and safety conditions — with official or primary sources before relying on them.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">5. No Guarantee of Outcomes</h2>
           <p>Roami AI™ provides informational guidance only and does not guarantee any specific outcome, experience, or condition. Recommendations are based on available data and AI analysis and may not reflect current real-world circumstances.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">6. Location Data Disclaimer</h2>
           <p>Location-based insights provided by the App may not reflect real-time or accurate local conditions. You are solely responsible for exercising personal judgment and taking appropriate precautions when navigating unfamiliar places. The App's use of your location data is further described in our Privacy Policy.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">7. Privacy & Data Collection</h2>
           <p className="mb-3">Your use of the App is also governed by our Privacy Policy, which is incorporated into this Agreement by reference. By using the App, you consent to the collection, use, and sharing of your information as described therein. We may collect the following types of data:</p>
           <ul className="list-disc pl-6 space-y-2 mb-3">
             <li>Location data (when permitted by your device settings)</li>
             <li>Usage data and interaction history within the App</li>
             <li>Device identifiers and operating system information</li>
             <li>Any information you voluntarily provide (e.g., travel preferences, profile details)</li>
           </ul>
           <p>We do not sell your personal data to third parties. You may withdraw consent for certain data collection at any time through your device settings, though doing so may limit App functionality.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">8. Third-Party Services & Integrations</h2>
           <p className="mb-3">The App may integrate with or link to third-party services, platforms, APIs, or content providers (collectively, "Third-Party Services"), including but not limited to mapping services, AI model providers, booking platforms, and transit data sources. You acknowledge that:</p>
           <ul className="list-disc pl-6 space-y-2">
             <li>Third-Party Services are governed by their own terms of service and privacy policies.</li>
             <li>Roami AI™ does not endorse, control, or guarantee the accuracy or availability of Third-Party Services.</li>
             <li>Roami AI™ is not liable for any loss or harm arising from your use of or reliance on Third-Party Services.</li>
           </ul>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">9. User Responsibility</h2>
           <p>You are solely responsible for your travel decisions, actions, and safety. Roami AI™ is a decision-support tool. Nothing in the App constitutes professional travel, legal, medical, or safety advice.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">10. Acceptable Use</h2>
           <p className="mb-3">You agree to use the App only for lawful purposes and in accordance with this Agreement. You agree not to:</p>
           <ul className="list-disc pl-6 space-y-2">
             <li>Use the App for any unlawful, fraudulent, or harmful purpose</li>
             <li>Attempt to reverse-engineer, decompile, or extract source code from the App</li>
             <li>Use the App to infringe upon the rights of any third party</li>
             <li>Introduce malware, viruses, or disruptive code into the App or its systems</li>
             <li>Use automated tools to scrape, extract, or misuse App content</li>
           </ul>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">11. Intellectual Property</h2>
           <p>All content, features, branding, trademarks, and technology within the App — including the Roami AI™ name, logo, Energy Pillar framework, and associated intellectual property — are owned by or licensed to Whitney Justine, LLC. This Agreement does not grant you any right to use our trademarks, trade names, or branding without prior written consent. Unauthorized reproduction, distribution, or commercial use of any App content is strictly prohibited.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">12. Limitation of Liability</h2>
           <p className="uppercase font-semibold">To the fullest extent permitted by applicable law, Roami AI™ and Whitney Justine, LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, personal injury, or property damage, arising out of or related to your use of or inability to use the App, even if advised of the possibility of such damages. The App is provided "as is" and "as available" without warranties of any kind, express or implied.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">13. Dispute Resolution</h2>
           <p>Any dispute, claim, or controversy arising out of or relating to this Agreement or the App shall first be attempted to be resolved through good-faith negotiation between the parties. If negotiation fails, disputes shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association, conducted in the State of North Carolina. You waive any right to participate in a class action lawsuit or class-wide arbitration. Nothing in this section prevents either party from seeking emergency injunctive relief from a court of competent jurisdiction.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">14. Updates to App & Agreement</h2>
           <p>We may update the App or this Agreement at any time. Continued use of the App following notice of material changes constitutes your acceptance of the updated terms. We encourage you to review this Agreement periodically.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">15. Termination</h2>
           <p>We reserve the right to suspend or terminate your access to the App at any time, with or without notice, if we believe you have violated this Agreement or applicable law. Upon termination, all licenses granted herein shall immediately cease.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">16. Governing Law</h2>
           <p>This Agreement shall be governed by and construed in accordance with the laws of the State of North Carolina, United States, without regard to its conflict of law provisions.</p>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4 text-foreground">17. Severability</h2>
           <p>If any provision of this Agreement is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>
        </section>

        <section className="p-6 bg-surface border border-border rounded-2xl mt-8">
           <h3 className="text-xl font-bold mb-2 text-foreground">18. Contact</h3>
           <p className="mb-2">If you have any questions, concerns, or requests regarding this Agreement or our privacy practices, please contact us at:</p>
           <p className="font-semibold text-foreground">Roami AI™ | Whitney Justine, LLC</p>
           <p>Email: <a href="mailto:getroamiai@gmail.com" className="text-primary hover:underline">getroamiai@gmail.com</a></p>
        </section>

        <div className="pt-8 border-t border-border mt-8 text-sm text-center">
           <p>© 2026 Whitney Justine, LLC. All rights reserved. Roami AI™ is a trademark of Whitney Justine, LLC.</p>
        </div>
      </div>
    </div>
  );
}
